export enum MotifSanction{
    JEUDI_PROPRE = 'ABSENCE JEUDI PROPRE',
    ABSENCE_JUSTIFIE = 'ABSENCE JUSTIFIEE',
    ABSENCE_NON_JUSTIFIE = 'ABSENCE NON JUSTIFIEE',
    VAGABONDAGE_INSUBORDINATION = 'VAGABONDAGE ET INSUBORDINATION',
    DISTRACTION = 'DISTRACTION AUX HEURES DE SERVICES',
    SOMMEIL = 'SOMMEIL EN PLEIN SERVICE',
    SUSPENSION_TMP = 'SUSPENSION TEMPORAIRE',
    CONSOMMATION = 'CONSOMMATION DE BOISSONS AUX HEURES DE SERVICE',
    RETARD_NON_JUSTIFIE = 'RETARD NON JUSTIFIE'

}